### ISSUE TITLE
Upgrade to Angular 7

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular-charts#14]
`igniteui-angular` has already upgraded to Angular 7. But, `igniteui-angular-charts` hasn't yet.

Do you have a plan to upgrade `igniteui-angular-charts` to Angular 7?

**Comment by gmurray81** [comment]
Yes. In progress. But you can already upgrade to Angular 7, we haven't seen any issues.

**Comment by tkiryu** [comment]
@gmurray81 , I confirmed [v7.2.0](https://www.npmjs.com/package/igniteui-angular-charts) has been released already. Thanks!

Closing this issue.
