### ISSUE TITLE
Bug: igx-axis-component calls console.log()

### ISSUE THREAD

**Issue by ymita** [IgniteUI/igniteui-angular-charts#15]
## Description  
console.log() method remains in igx-axis-component.js

 * igniteui-angular-charts version: 7.2.0
 * browser: n/a

## Steps to reproduce  

1. Run the attached sample
2. Open the browser console

## Result  
igx-axis-component.js calls console.log() inside. So that the log is printed on the browser's console.
![image](https://user-images.githubusercontent.com/14340675/54979726-3f53b180-4fe7-11e9-8b81-9a43f1ec0f64.png)

## Expected result  
console.log() does not remain.

## Attachments  
[igx-data-chart.zip](https://github.com/IgniteUI/igniteui-angular-charts/files/3007031/igx-data-chart.zip)

**Comment by mddifilippo89** [comment]
Thank you! We've logged this under review to investigate. 

#263212

**Comment by gmurray81** [comment]
This is fixed
