### ISSUE TITLE
Upgrade to angular 8

### ISSUE THREAD

**Issue by eestein** [IgniteUI/igniteui-angular-charts#17]
Hi, I'm already on version 8 of angular, but the charts plugin is not working with this version. The regular igniteui-angular is already on version 8. Any idea on when the charts will support angular 8?

One issue I've seen so far:

> ERROR in ./node_modules/igniteui-angular-charts/ES5/igx-pie-chart-component.js 160:34-42
"export 'DOCUMENT' was not found in '@angular/platform-browser'

**Comment by Lipata** [comment]
@eestein, please try [v.8.0.0-beta.0](https://www.npmjs.com/package/igniteui-angular-charts/v/8.0.0-beta.0) for all the chart libraries. I will update the issue when the official version of the packages are available.

**Comment by eestein** [comment]
@Lipata thanks, it's working now

**Comment by Lipata** [comment]
@eestein you can switch to the official 8.0.0 version.
