### ISSUE TITLE
Slider in Real Time Chart sample not working correctly 

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular-charts#2]
### Steps to reproduce  
Run sample:
https://www.infragistics.com/products/ignite-ui-angular/angular/components/categorychart_real_time_data.html
move number of rows slider. 
Move it back.

### Result  
It seems to only bounce between maxPoints and maxPoints - 1. 
If you open the sample in stackblitz and set [isContinuous]=false you can see the values more clearly

### Expected result  
The slider should slide between values like the refresh rate one does

**Comment by gmurray81** [comment]
@agoldenbaum  did you look at this yet?

**Comment by mddifilippo89** [comment]
Sliders were removed from the sample on our website for the time being.
