### ISSUE TITLE
Hover / highlighting

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular-charts#24]
@gmurray81 I'm having a hard time figuring out hover om a column series. There is a setting called highlighting, but this seems to only be a on/off thing. What if I want to have a custom color (unrelated to the brushes) on hover? Is this possible?

**Comment by gmurray81** [comment]
Hi,
You can actually customize the highlighting a great deal with the assigningCategoryStyle event. Please see this sample:
https://stackblitz.com/edit/custom-highlighting?file=src/app/data-chart-type-category-series/data-chart-type-category-series.component.ts

**Comment by Eralmidia** [comment]
Thanks, this seems to be working fine. One follow up question tho: in the samples, your brush color is hard coded by
```
public seriesR = 0;
public seriesG = 255;
public seriesB = 0;
```

We generally have a bit more dynamic system, with services streaming the brushes depending on user theme etc. If the brush is more dynamic, would the most efficient way to get the brush be parsing the brush property from the sender, something like this?
![image](https://user-images.githubusercontent.com/12936286/67778568-a779e280-fa63-11e9-95df-2bd01fb75d1f.png)

**Comment by gmurray81** [comment]
yes, you can make it more dynamic. I did it this way for the sake of simplicity. You can also acquire the current fill or stroke brushes from the args, but please note these may be resolved values, that could be in rgba format rather than rgb, so the parsing may not be as simple as you've laid out.

**Comment by Eralmidia** [comment]
I see that if a do a bit more advanced brush with gradient: 
![image](https://user-images.githubusercontent.com/12936286/67835286-da66b980-fae9-11e9-9b1e-0ea6e26ed044.png)
the brush property ends up being `null`. Is there no way to get a hover color on a brush like that? Seems like it should be, since the native chart highlighting works?
