### ISSUE TITLE
Limit column width

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular-charts#25]
@gmurray81 Is it possible to limit the width of columns? If you only have a coluple of columns, they get very large: 
![image](https://user-images.githubusercontent.com/12936286/67665928-f7c14980-f96a-11e9-8d8a-586ba624ccd0.png)

**Comment by gmurray81** [comment]
This is adjustable, to a degree, by using the `gap` property on the category x axis, which controls the amount of spacing between the categories. There is a limit, currently, to how far this lets you reduce the width of the column, however, as I believe the value get's clamped. Let me know if it works for your or whether you need a way of reducing the column width further.

**Comment by Eralmidia** [comment]
@gmurray81 Thanks. That helps a bit, but not really that much. The clamping (which I assume is at 1), still makes for very large columns:
![image](https://user-images.githubusercontent.com/12936286/67772060-bb204b80-fa59-11e9-8b61-46aa39027b4d.png)

Also, if the number of columns is dynamic, which is often the case, a gap of 1 may seem as too much in other cases.  The latter issue I assume is possible to work around by applying some simple math to the gap input based on number of columns, but the max gap is a bit unfortunate.

**Comment by gmurray81** [comment]
You aren't the first person to run into this limitation. I can't really see a good rational for clamping the limit, so I think we may remove this. I think for your scenario, though, perhaps being able to specify a `maxWidth` might be most useful?

**Comment by Eralmidia** [comment]
Yes, setting a `maxWidth` of the columns, and getting dynamic gap, would absolutely be the easiest to use.

**Comment by Eralmidia** [comment]
Since I'm not the first to run into this, is this something which will be coming soon?
