### ISSUE TITLE
Angular 9

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular-charts#32]
When can we expect Angular 9 support? The rest of the igx components have had support for this for some time now, and the chart package is blocking us from moving to v9.

**Comment by Lipata** [comment]
[8.2.12](https://www.npmjs.com/package/igniteui-angular-charts) is ng 9 compatible.

**Comment by Eralmidia** [comment]
@Lipata Thanks 🙂 Just assumed we had to wait for a 9.x
