### ISSUE TITLE
Is there a way to customize the tooltip that is shown while hovering Radial Pie Chart?

### ISSUE THREAD

**Issue by luiscla27** [IgniteUI/igniteui-angular-charts#33]
Is there a way to customize the `tooltip` that is shown while hovering the Radial Pie Chart?
![image](https://user-images.githubusercontent.com/29953012/74770249-7eb76c00-5251-11ea-9623-b9a5c8834ec9.png)

I tried setting the `title` attribute without success, test here: https://stackblitz.com/edit/click-igx-chart-type-radial-pie-series

**Comment by mddifilippo89** [comment]
Hello 

The root DataChart already has a Title property which, in the sample, is set to "COMPANY FINANCES BY DEPARTMENT"

**Comment by mddifilippo89** [comment]
The root DataChart also contains a subtitle property. 
eg. 

<igx-data-chart #chart
            [legend]=legend
            chartTitle="COMPANY FINANCES BY DEPARTMENT"
            subtitle="test"

**Comment by luiscla27** [comment]
Thank you for your quick answer @mddifilippo89, I think i asked the wrong question, I've modified it to clarify. 

The `title` property doesn't fulfill my requirement, I've found [this documentation](https://www.infragistics.com/products/ignite-ui-angular/angular/components/data-chart-series-tooltips.html) which explains about the `showDefaultTooltip` attribute, how ever, is there a way to add custom data to it?

**Comment by mddifilippo89** [comment]
Yes, you can use the tooltipTemplate property on the RadialPieSeriesComponent paired with an NgTemplate with complex bindings.

eg. 
<igx-radial-pie-series [tooltipTemplate]="valueTooltip" ..>

<ng-template let-series="series" let-item="item" #valueTooltip>
   <div>
      <span> Marketing:{{item.Marketing| number}}<br/></span>
    </div>
</ng-template>

It should work exactly like this sample
https://www.infragistics.com/products/ignite-ui-angular/angular/components/category-chart-tooltip-template.html

**Comment by luiscla27** [comment]
Thank you again, i've managed to make it work at [the same test](https://stackblitz.com/edit/click-igx-chart-type-radial-pie-series) i was working with.
