### ISSUE TITLE
Change location of igx tooltip in igx-chart

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular-charts#38]
It seems like the igx-charts renders tooltips within the chart, and not on the igx-overlay. Could this be changed please? If a parent container of the chart has overflow: auto/scroll, the tooltip causes a scrollbar as well:
![image](https://user-images.githubusercontent.com/12936286/87001390-9cad4b00-c1b7-11ea-9893-22b2a7619ac7.png)

**Comment by Eralmidia** [comment]
I also tried the tooltipTemplateContainer input. This isn't very well documented, but I assumed it could be used to assign another container for the tooltip, rather than the chart itself, but this didn't seem to do anything...

**Comment by agoldenbaum** [comment]
I am marking this issue as closed, as it is currently being handled through the Infragistics support system in a private support case, CAS-208517-S9N3K0.

**Comment by mddifilippo89** [comment]
You can resolve this with a small margin on the chart and ensure all the containers, including the chart have a width of 100%. 

https://stackblitz.com/edit/github-bkjbx6-g9qou1
