### ISSUE TITLE
Error occurs "NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class." during building an app.

### ISSUE THREAD

**Issue by norikois** [IgniteUI/igniteui-angular-charts#40]
## Description  
Error occurs "NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class." during building an app.

 * igniteui-angular version: 10.1.7
 * browser: N/A

## Steps to reproduce  

1. "npm install" and "ng serve" the attached sample application.

## Result  
Error occurs:

ERROR in node_modules/igniteui-angular-gauges/lib/igx-radial-gauge-component.d.ts:20:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

This likely means that the library (igniteui-angular-gauges) which declares IgxRadialGaugeComponent has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

20 export declare class IgxRadialGaugeComponent implements AfterContentInit, OnDestroy {

![ScreenShot1](https://user-images.githubusercontent.com/33947244/95040702-65472f80-070f-11eb-8aab-1a5b9b784e1c.png)

## Expected result  
The error does not occur and the application is successfully built

## Attachments  
Attach a sample if available, and screenshots, if applicable.  
[cas33469-app1.zip](https://github.com/IgniteUI/igniteui-angular/files/5325240/cas33469-app1.zip)

**Comment by kdinev** [comment]
@gmurray81 Could somebody take a look at this issue?

**Comment by gmurray81** [comment]
@norikois, sorry about that! There's a typo in the documentation. It's saying you should add both `IgxRadialGaugeModule` and `IgxRadialGaugeComponent` to the imports of the module, but this is incorrect, and you should only add `IgxRadialGaugeModule` to the imports:

```ts
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    IgxRadialGaugeModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule {
}
```

I'll make sure this is corrected in the documentation. 

Hope this helps!

**Comment by gmurray81** [comment]
P.S. I checked and your sample works fine without the extra import.
