### ISSUE TITLE
Pie and doughnut chart samples on docs page are broken

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular-charts#41]
![image](https://user-images.githubusercontent.com/12936286/98858088-56ffd800-2460-11eb-838f-3efff8280087.png)

**Comment by mddifilippo89** [comment]
Our stackblitz samples are currently missing imports in the app.module.ts. If you are running into these issues on our website directly please let me know as soon as possible.

A quick solution would be to open app.module.ts hover over the missing components and choose "quick fix". You can also refer to this modified version here:

https://stackblitz.com/edit/github-gcrp9n?file=src/app/app.module.ts
