### ISSUE TITLE
ignite ui-angular-excel load error

### ISSUE THREAD

**Issue by wiltwitt** [IgniteUI/igniteui-angular-charts#43]
## Description  
Warning: Entry point 'igniteui-angular-excel' contains deep imports into 'C:/site/www/node_modules/jszip/dist/jszip'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
Compiling igniteui-angular-excel : es2015 as esm2015
Compiling igniteui-angular-spreadsheet : es2015 as esm2015
93% after chunk asset optimization SourceMapDevToolPlugin vendor.js generate SourceMap
<--- Last few GCs --->

[42664:000001156F32A4F0]   250100 ms: Mark-sweep 1953.4 (2062.3) -> 1951.8 (2061.8) MB, 2031.2 / 0.0 ms  (average mu = 0.106, current mu = 0.005) allocation failure scavenge might not succeed
[42664:000001156F32A4F0]   251793 ms: Mark-sweep 1955.2 (2061.8) -> 1953.9 (2063.3) MB, 1685.8 / 0.0 ms  (average mu = 0.057, current mu = 0.005) allocation failure scavenge might not succeed

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 00007FF77266170D]
    1: StubFrame [pc: 00007FF772639FEA]
Security context: 0x03eaa6740911 <JSObject>
    2: match [000003EAA6751C91](this=0x031dd8fc7431 <String[7]\:     }\r\n>,0x00e98905d629 <JSRegExp <String[#26]: (?!$)[^\n\r;{}]*[\n\r;{}]*>>)
    3: /* anonymous */(aka /* anonymous */) [000003B9AB298401] [C:\site\www\node_modules\webpack-sources\lib\OriginalSource.js:~36] [pc=0000017166F8228B](this=0x00c4f...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

Writing Node.js report to file: report.20210211.120254.42664.0.001.json
Node.js report completed
 1: 00007FF771E2962F napi_wrap+122319
 2: 00007FF771DD2376 public: bool __cdecl v8::base::CPU::has_sse(void)const __ptr64+34454
 3: 00007FF771DD3036 public: bool __cdecl v8::base::CPU::has_sse(void)const __ptr64+37718
 4: 00007FF7725B8A1E private: void __cdecl v8::Isolate::ReportExternalAllocationLimitReached(void) __ptr64+94
 5: 00007FF7725A0D6A public: class v8::SharedArrayBuffer::Contents __cdecl v8::SharedArrayBuffer::Externalize(void) __ptr64+842
 6: 00007FF77243256C public: static void __cdecl v8::internal::Heap::EphemeronKeyWriteBarrierFromCode(unsigned __int64,unsigned __int64,class v8::internal::Isolate * __ptr64)+1436
 7: 00007FF77243A48F public: unsigned __int64 __cdecl v8::internal::Heap::OldGenerationSizeOfObjects(void) __ptr64+4879
 8: 00007FF772430733 public: bool __cdecl v8::internal::Heap::CollectGarbage(enum v8::internal::AllocationSpace,enum v8::internal::GarbageCollectionReason,enum v8::GCCallbackFlags) __ptr64+1235 9: 00007FF77242EFC4 public: void __cdecl v8::internal::Heap::AddRetainedMap(class v8::internal::Handle<class v8::internal::Map>) __ptr64+2292
10: 00007FF77244DAA5 public: class v8::internal::Handle<class v8::internal::HeapObject> __cdecl v8::internal::Factory::NewFillerObject(int,bool,enum v8::internal::AllocationType) __ptr64+53
11: 00007FF772203E0D public: class v8::internal::interpreter::JumpTableTargetOffsets::iterator & __ptr64 __cdecl v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator=(class v8::internal::interpreter::JumpTableTargetOffsets::iterator && __ptr64) __ptr64+3757
12: 00007FF77266170D public: virtual bool __cdecl v8::internal::SetupIsolateDelegate::SetupHeap(class v8::internal::Heap * __ptr64) __ptr64+614605
13: 00007FF772639FEA public: virtual bool __cdecl v8::internal::SetupIsolateDelegate::SetupHeap(class v8::internal::Heap * __ptr64) __ptr64+453034
14: 00007FF7726492CC public: virtual bool __cdecl v8::internal::SetupIsolateDelegate::SetupHeap(class v8::internal::Heap * __ptr64) __ptr64+515212
15: 0000017166F8228B 
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! portal@1.0.0 start: `ng serve`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the portal@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\me\AppData\Roaming\npm-cache\_logs\2021-02-11T17_02_56_922Z-debug.log

 * igniteui-angular version:  9.1.12
 * browser: chrome

## Steps to reproduce  

1. add ignite ui-angular-excel npm package.  Followed https://www.infragistics.com/products/ignite-ui-angular/angular/components/spreadsheet-overview

## Result  
fails to run the app

**Comment by kdinev** [comment]
@igandrews @gmurray81 Can somebody take a look at this issue?

**Comment by igandrews** [comment]
I've seen this happen in the past although I didn't get it when I tried with the same version listed. It's not anything that we have direct control over though. It seems like the sourcecodemap uses a lot of heap and because those libraries are large it may end up overflowing. There's a couple of ways to continue. One would be to just disable the source maps. The other would be to increase the node heap size. I think there's a NODE_OPTIONS environment variable but you could also just change the scripts within the package.json.

"build": "node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build",
"start": "node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng serve",

**Comment by igandrews** [comment]
Yes I think that makes sense.

**Comment by igandrews** [comment]
BTW if it is those source maps that are causing the issue then one could disable vendor source maps - which afaik defaults to off. https://angular.io/guide/workspace-config#source-map-configuration
