### ISSUE TITLE
using too much memory with ES5 compilerOptions and Polyfills - error in IE11

### ISSUE THREAD

**Issue by loclv** [IgniteUI/igniteui-angular-charts#44]
## Environment

- Browser: IE11
- Angular: `~11.2.7`

## Problems

You can use [this demo repository](https://github.com/loclv/ie-igniteui-angular-charts-demo) for debugger.

1. Run develop server with with ES5 `compilerOptions` and `Polyfills`.
```sh
yarn ie
```
2.  Run in IE11
3. You can see error in `Polyfills` bundle.

If you check Network tab, `vendor.js` size is too big.

![igx-chart-err](https://user-images.githubusercontent.com/6302717/113401218-3adbe380-93cd-11eb-8a69-0da8b6f91ff9.png)

if run with `yarn start`, `vendor.js` size is ~15MB.

**Comment by mddifilippo89** [comment]
Hi, I reproduced the behavior, but I am still investigating this.

**Comment by mddifilippo89** [comment]
Hello, 

I discussed this with my team and the vendor size is perfectly normal when _not_ running in production. It's because it contains comments and source mappings. If you are continuing to see this size in production let us know.

**Comment by loclv** [comment]
Hello,
I think i can't use `igniteui-angular-charts` for IE11, because this problem in dev-mode.
Thank for your support!
