### ISSUE TITLE
Support for angular 12?

### ISSUE THREAD

**Issue by eestein** [IgniteUI/igniteui-angular-charts#45]
Hi, when will we have support for angular 12? 
It seems to be working on my project, but I keep getting these warnings:

> 
> npm WARN igniteui-angular-charts@11.2.0 requires a peer of @angular/common@^11.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN igniteui-angular-charts@11.2.0 requires a peer of @angular/compiler@^11.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN igniteui-angular-charts@11.2.0 requires a peer of @angular/core@^11.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN igniteui-angular-core@11.2.0 requires a peer of @angular/common@^11.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN igniteui-angular-core@11.2.0 requires a peer of @angular/compiler@^11.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN igniteui-angular-core@11.2.0 requires a peer of @angular/core@^11.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by agoldenbaum** [comment]
Hi eestein,
At the time of writing this, we do not have npm packages that directly target Angular 12, and that is the reason you are seeing these warnings, as it appears you are targeting Angular 12 with our packages that are built against Angular 11.

While I do not have an exact ETA on when we will be releasing Angular 12 packages, I would expect these to become available in  an upcoming release.

**Comment by Lipata** [comment]
@gmurray81, @agoldenbaum.

With Typescript 4.3 (required by Angular 12.1), there is a breaking change that removes the usage of `MSPointerEvents` and `MSGestureEvents`, events that are used in the `igniteui-angular-core` package:

![image](https://user-images.githubusercontent.com/2621802/127124818-f6b95ad6-58be-4e06-a808-4e71e2819f96.png)

Currently, this can be suppressed by setting `skipLibCheck: true` in the `tsconfig` file, however, we should consider fixing it.

**Comment by gmurray81** [comment]
We've made some updates for the DV components to avoid the conflicts with the recent TS deprecations. This is under test ATM and a new set of packages should be available soon.
