### ISSUE TITLE
X-Axis Scaling

### ISSUE THREAD

**Issue by Timmeeeey** [IgniteUI/igniteui-angular-charts#47]
I have a line chart with the following data:
`[{ x: 0, y: 11 }, { x: 1, y: 10 }, { x: 2: y: 11 }, { x: 4: y: 12 }, { x: 8: y: 13 }]`
The x-axis shows 0, 1, 2, 4 and 8 with equal distance.
`0--1--2--4--8`
Is it possible to scale the x-axis like the y-axis so 4 is twice as far from 2 as 2 from 1?
`0--1--2----4--------8`

**Comment by agoldenbaum** [comment]
Hi Timmeeeey,

If you are using a line chart, as you have mentioned, I am under the impression that you are using the IgxCategoryXAxis. This axis has a **discrete** scale, which means that it will only draw a scale for the categories that correspond to your data items, and it will space them evenly. If you are looking for more of a continuous scale, I would recommend using the IgxNumericXAxis and use the IgxScatterLineSeries instead. You can read about usage of the IgxScatterLineSeries here: https://www.infragistics.com/products/ignite-ui-angular/angular/components/charts/types/scatter-chart#angular-scatter-line-chart.

I hope this helps. Please let me know if you have any other questions or concerns on this matter.

Sincerely,
Andrew Goldenbaum
Software Developer – Team Lead
Infragistics

**Comment by Timmeeeey** [comment]
Ok, thank you.
Is it possible to configure the x-axis to display only the existing values from the dataset like `0--1--2----4--------8`?

**Comment by agoldenbaum** [comment]
You can configure the X-Axis to only display the existing values from your data set by setting the Interval property of the axis to 1, and then handling the FormatLabel event. The FormatLabel event handler requires a string to be returned, and if there is a label you do not want to show, you can return an empty string for it. Here's a link to our API entry for the FormatLabel event: https://www.infragistics.com/products/ignite-ui-angular/api/docs/typescript/latest/classes/igxnumericxaxiscomponent.html#formatlabel

**Comment by Timmeeeey** [comment]
Ah thank you that's what I needed.
