### ISSUE TITLE
Support for angular 13

### ISSUE THREAD

**Issue by IvayloG** [IgniteUI/igniteui-angular-charts#51]
@gmurray81
`igniteui-angular-core` may require a fix & a version bump, as with the latest 12.1.1 it throws MSGesture error
![image](https://user-images.githubusercontent.com/4296944/140491196-7ae0ae5b-c5fc-4753-9db1-0a10d43dffaa.png)

**Reproduce context:**
Testing via the igniteui-cli (ng13 & igniteui-angular": "~13.0.0-alpha.3) - building an **igx-ts** project that includes components requiring `igniteui-angular-core`  throws the error.

**Comment by gmurray81** [comment]
We have this fixed internally but I guess the package hasn't been published yet. Will ask around.

**Comment by gmurray81** [comment]
Published as 12, should be published soon as 13 too

**Comment by Lipata** [comment]
Thank you, @gmurray81!
