### ISSUE TITLE
Financial Data Charts range selector not rendered

### ISSUE THREAD

**Issue by KaushikEDS** [IgniteUI/igniteui-angular-charts#52]
## Question  
I am providing data to Financial charts and I cant see the range when I load data from my API.
Real Time Chart with missing range selector:-
![image](https://user-images.githubusercontent.com/79090369/147478136-6a7cde60-3658-44d9-850a-db816820c8ec.png)

Real Time Chart data in console :-
![image](https://user-images.githubusercontent.com/79090369/147474801-c09d305b-9fa5-4a1d-8f3f-679fec75f0aa.png)

But when I load mock data it shows the range selector. 
Mock Data Chart :-

![image](https://user-images.githubusercontent.com/79090369/147473109-47744a9e-c6a8-4a27-858a-65205524a2a7.png)

You can see the data I pass to the component in the console.
![image](https://user-images.githubusercontent.com/79090369/147473201-61b09bf0-1065-4894-b757-1e4c2044ceb4.png)

Mock Data JSON link : https://paste.ofcode.org/WdHQqc22yUGyQ7CKMjmdPp

Real Data JSON link : https://paste.ofcode.org/ESaCXCkJH9EvguKuxi36VA

**Comment by ChronosSF** [comment]
@hanastasov , @KaushikEDS , just wanted to let you know that I transferred the issue in this repository.
