### ISSUE TITLE
Feature request: click event emitters in charting components

### ISSUE THREAD

**Issue by rkara** [IgniteUI/igniteui-angular-charts#6]
The [ui.igDataChart](https://www.igniteui.com/help/api/2018.1/ui.igDataChart) had several events, including `seriesMouseLeftButtonDown` to handle clicking a series within a chart.  It would be beneficial for such an event to be emitted by the [Category Chart](https://www.infragistics.com/products/ignite-ui-angular/angular/components/categorychart.html).

I am not aware if this feature already exists, but if it does I cannot find documentation for it.

**Comment by gmurray81** [comment]
Sorry for the delay, you can use the seriesPointerDown, etc, events on igx-category-chart. See this example: https://stackblitz.com/edit/angular-am8qge-e5dels?file=app%2Fcategory-chart%2Fconfig-options%2Fcategory-chart-config-options-sample.component.ts

**Comment by gmurray81** [comment]
@pamelabrasil @HUSSAR-mtrela  do you know if this is documented anywhere? Seems like we should have a sample for events.

**Comment by rkara** [comment]
@gmurray81 thank you for the response.  This works!  I did not see this documented on the [main category chart page](https://www.infragistics.com/products/ignite-ui-angular/angular/components/categorychart.html)

**Comment by gmurray81** [comment]
Yes, might be missing... There's much a more extensive API doc site coming quite soon, we've been having to overcome/fix limitations in the documentation generation tools first.

**Comment by rkara** [comment]
Great!  Thank you! @gmurray81
