### ISSUE TITLE
Feature request: Series gradients

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular-charts#8]
I didn't get a reply in #3, so I'll assume this is not implemented. 

Since we are doing a rewrite, we would like to freshen up the looks as well. Is it possible to configure a line/area chart with a combination of gradients and transparency, similar to this: https://cdn-images-1.medium.com/max/2000/1*Dc_ghRRz_QPo-yoOUaCe9Q.png ?

**Comment by gmurray81** [comment]
https://stackblitz.com/edit/angular-am8qge?file=app%2Fcategory-chart%2Fconfig-options%2Fcategory-chart-config-options-sample.component.html
