### ISSUE TITLE
Infinite calling on getters  in templates with IgxFinancialChart

### ISSUE THREAD

**Issue by HristoP96** [IgniteUI/igniteui-angular-charts#9]
**Description**
When we have *igx-financial chart* in a template, with or without other components within, every getter bound to a property is called infinite times. 

![infintegettercalling](https://user-images.githubusercontent.com/25771040/48142859-4be4a100-e2b6-11e8-92d7-b36e79a8ad09.PNG)

**Steps to Reproduce**
Open this sample in StackBlitz:
[https://stackblitz.com/edit/angular-chart-infinite-getter-call](https://stackblitz.com/edit/angular-chart-infinite-getter-call)
 
Open the browser console.

**Result**
Infinite calling of the getters bound to the chart and list item properties.

**Comment by gmurray81** [comment]
Good find guys. There was a nasty feedback loop between the chart and the zoomslider that cropped up last release, that we needed to squash, and I bet it has resurfaced somehow. Will investigate. Not sure why I'm not getting proper notifications for these. I think I must have turned off too many github notifications...

**Comment by gmurray81** [comment]
Hmm... no I think something more benign might be going on.... I think its just hearbeat resize checks, but I'm not sure why they'd be triggering a change detection since they are executed outside of the angular zone... odd.

**Comment by gmurray81** [comment]
strange.... not seeing the issue locally.... I wonder if something was altered with `runOutsideAngular` and the change detector in newer Angular versions, since I think I'm using 6 in my local sample....

**Comment by gmurray81** [comment]
I see what this is, but, BTW, you should definitely have OnPush set to the change detection strategy for any sample containing FinChart, or any of the charts, really, since you wouldn't want it to periodically rescan a big data set.

**Comment by gmurray81** [comment]
in this instance, once every some number of milliseconds (200 I think?) something is checking to see if zoomSlider needs to be resized, which is inadvertedly triggering a change detection. So it isn't an infinite issue, per se, and will be resolved soon, but the sample still should be using OnPush, especially since it seems like FC might trigger a set of change detections while building its initial layout that could be a perf issue if the CD is expensive. Will investigate making sure it only triggers one CD during initial layout.

**Comment by zdrawku** [comment]
Thank you for the detailed explanation Graham! We've made all [changes ](https://github.com/IgniteUI/crypto-portfolio-app/pull/24/files#diff-215e63ce91a56f9bcbb3dd0a7a083362R27) proposed by you and everything works smoothly.

**Comment by gmurray81** [comment]
Awesome. I'm going to make some changes in FC to reduce the number of change detections fired also, so I'll leave this open.

**Comment by gmurray81** [comment]
This will be resolved in the next release.

**Comment by gmurray81** [comment]
Note, though, it is still the best idea to use OnPush for any component containing a chart.
